/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fgs.fsc_attendencesystem;

import FourGenius.MC_JavaDataBaseConnection;
import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author deepalsuranga
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public static boolean flag = false;
    private static final String VOICENAME = "kevin16";

    public index() {
        initComponents();
        tf_manuwal.setEnabled(false);
        tf_rf.setEnabled(false);
        tf_qr.setEnabled(false);
        jc_qr.setVisible(false);
        jc_rf.setVisible(false);
        jc_manual.setVisible(false);
        logging.setVisible(false);
        _pf_user_login_password.setEditable(false);
        lb_ok_id.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logging = new javax.swing.JPanel();
        _tf_user_login_username = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        _lb_user_login_showPassword = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        _pf_user_login_password = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_rf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_qr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf_manuwal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lb_ok_id = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jc_qr = new javax.swing.JCheckBox();
        jc_rf = new javax.swing.JCheckBox();
        jc_manual = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logging.setBackground(new java.awt.Color(0, 153, 255));
        logging.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        _tf_user_login_username.setMaximumSize(new java.awt.Dimension(383, 35));
        _tf_user_login_username.setMinimumSize(new java.awt.Dimension(383, 35));
        _tf_user_login_username.setPreferredSize(new java.awt.Dimension(383, 35));
        _tf_user_login_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_user_login_usernameActionPerformed(evt);
            }
        });
        logging.add(_tf_user_login_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 315, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Username");
        logging.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Password");
        logging.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        _lb_user_login_showPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _lb_user_login_showPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fsc_attendencesystem/img_ShowPassword.png"))); // NOI18N
        _lb_user_login_showPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _lb_user_login_showPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _lb_user_login_showPasswordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                _lb_user_login_showPasswordMouseReleased(evt);
            }
        });
        logging.add(_lb_user_login_showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 28, 35));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("X");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        logging.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 22, 23));

        _pf_user_login_password.setMaximumSize(new java.awt.Dimension(35, 20));
        _pf_user_login_password.setMinimumSize(new java.awt.Dimension(35, 20));
        _pf_user_login_password.setPreferredSize(new java.awt.Dimension(35, 20));
        _pf_user_login_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _pf_user_login_passwordMouseClicked(evt);
            }
        });
        _pf_user_login_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _pf_user_login_passwordActionPerformed(evt);
            }
        });
        logging.add(_pf_user_login_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 315, 35));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fsc_attendencesystem/green-lock.png"))); // NOI18N
        jLabel12.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel12.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel12.setPreferredSize(new java.awt.Dimension(80, 80));
        logging.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 260));

        getContentPane().add(logging, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 560, 260));

        jPanel6.setBackground(new java.awt.Color(0, 153, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Code Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RF Code System");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 388, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fsc_attendencesystem/lab_pass.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 55, 200, 270));

        tf_rf.setEditable(false);
        tf_rf.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tf_rfPropertyChange(evt);
            }
        });
        tf_rf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_rfKeyTyped(evt);
            }
        });
        jPanel4.add(tf_rf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 380, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Scan RF Card");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Name Load Here");
        jLabel17.setToolTipText("");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 340, 50));

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 128, -1, 475));

        jPanel2.setBackground(new java.awt.Color(65, 65, 65));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("X");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1313, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 1370, 150));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Code Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QR Code System");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 388, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fsc_attendencesystem/default_qrcode.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 190, 183));

        tf_qr.setEditable(false);
        tf_qr.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tf_qrPropertyChange(evt);
            }
        });
        tf_qr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_qrKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_qrKeyTyped(evt);
            }
        });
        jPanel3.add(tf_qr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 380, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Scan QR Code");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Name Load Here");
        jLabel16.setToolTipText("");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 340, 50));

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 128, -1, 475));

        jPanel1.setBackground(new java.awt.Color(65, 65, 65));

        jLabel1.setFont(new java.awt.Font("Code Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Attendece System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(479, 479, 479)
                .addComponent(jLabel1)
                .addContainerGap(641, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 2, 1410, 110));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Code Light", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Manual Code System");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 400, -1));

        tf_manuwal.setEditable(false);
        tf_manuwal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tf_manuwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_manuwalActionPerformed(evt);
            }
        });
        jPanel5.add(tf_manuwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 390, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Name Load Here");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 390, 53));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Enter Your Student ID:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(846, 128, -1, 475));

        lb_ok_id.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fsc_attendencesystem/welCome_correct.png"))); // NOI18N
        lb_ok_id.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(lb_ok_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 150, 60, 80));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 1417, 700));

        jButton1.setBorder(null);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1097, 0, -1, 70));

        jButton2.setText("LOG IN AND ACTIVAED SYSTEM");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1091, 70));

        jc_qr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jc_qr.setText("QR");
        jc_qr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jc_qr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jc_qr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jc_qr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jc_qr.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jc_qr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_qrActionPerformed(evt);
            }
        });

        jc_rf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jc_rf.setText("RF");
        jc_rf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jc_rf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jc_rf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jc_rf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jc_rf.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jc_rf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_rfActionPerformed(evt);
            }
        });

        jc_manual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jc_manual.setText("MANUAL");
        jc_manual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jc_manual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jc_manual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jc_manual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jc_manual.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jc_manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_manualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jc_qr, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jc_rf, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jc_manual, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jc_manual, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
            .addComponent(jc_rf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jc_qr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1104, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked

        System.exit(0);

    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        logging.setVisible(true);
        _tf_user_login_username.grabFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jc_rfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_rfActionPerformed

        if (flag) {
            System.out.println(flag);
            tf_rf.setEnabled(true);
            tf_rf.grabFocus();
            tf_qr.setEditable(false);
            tf_rf.setEditable(true);
            tf_manuwal.setEditable(false);
        }

        if (jc_rf.isSelected()) {
            jc_manual.setEnabled(false);
            jc_qr.setEnabled(false);
        }
        if (!(jc_rf.isSelected())) {
            jc_manual.setEnabled(true);
            jc_qr.setEnabled(true);
            tf_rf.setEnabled(false);
            tf_rf.setEditable(false);
        }

    }//GEN-LAST:event_jc_rfActionPerformed

    private void jc_qrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_qrActionPerformed

        if (flag) {
            tf_qr.setEnabled(true);
            tf_qr.setEditable(true);
            tf_rf.setEditable(false);
            tf_manuwal.setEditable(false);
            tf_qr.grabFocus();
        }
        if (jc_qr.isSelected()) {
            jc_manual.setEnabled(false);
            jc_rf.setEnabled(false);
        }
        if (!(jc_qr.isSelected())) {
            jc_manual.setEnabled(true);
            jc_rf.setEnabled(true);
            tf_qr.setEnabled(false);
            tf_qr.setEditable(false);
        }

    }//GEN-LAST:event_jc_qrActionPerformed

    private void _tf_user_login_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_user_login_usernameActionPerformed

        new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    ResultSet rs = MC_JavaDataBaseConnection.myConnection().createStatement().executeQuery("SELECT * FROM `user` WHERE user_email='" + _tf_user_login_username.getText() + "'");
                    if (rs.next()) {
                        _pf_user_login_password.setEditable(true);
                        _pf_user_login_password.grabFocus();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Wrong Username", "Warnning", 2);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();
    }//GEN-LAST:event__tf_user_login_usernameActionPerformed

    private void _lb_user_login_showPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lb_user_login_showPasswordMousePressed

        _pf_user_login_password.setEchoChar((char) 0);
    }//GEN-LAST:event__lb_user_login_showPasswordMousePressed

    private void _lb_user_login_showPasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lb_user_login_showPasswordMouseReleased

        _pf_user_login_password.setEchoChar('*');
    }//GEN-LAST:event__lb_user_login_showPasswordMouseReleased

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked

        logging.setVisible(false);

    }//GEN-LAST:event_jLabel15MouseClicked

    private void _pf_user_login_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__pf_user_login_passwordActionPerformed

        try {
            ResultSet rs = MC_JavaDataBaseConnection.myConnection().createStatement().executeQuery("SELECT * FROM `user` WHERE user_email='" + _tf_user_login_username.getText() + "' and user_password='" + _pf_user_login_password.getText() + "'");
            if (rs.next()) {
//
                jc_qr.setVisible(true);
                jc_rf.setVisible(true);
                jc_manual.setVisible(true);

                flag = true;

                logging.setVisible(false);
                System.out.println("ppp");

            } else {
                JOptionPane.showMessageDialog(rootPane, "Wrong Password", "Warnning", 2);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event__pf_user_login_passwordActionPerformed

    private void jc_manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_manualActionPerformed

        if (flag) {
            tf_manuwal.setEnabled(true);
            System.out.println(flag);
            tf_qr.setEditable(false);
            tf_rf.setEditable(false);
            tf_manuwal.setEditable(true);
            tf_manuwal.grabFocus();
        }
        if (jc_manual.isSelected()) {
            jc_qr.setEnabled(false);
            jc_rf.setEnabled(false);
        }
        if (!(jc_manual.isSelected())) {
            jc_qr.setEnabled(true);
            jc_rf.setEnabled(true);
            tf_manuwal.setEnabled(false);
            tf_manuwal.setEditable(false);
        }

    }//GEN-LAST:event_jc_manualActionPerformed

    private void _pf_user_login_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__pf_user_login_passwordMouseClicked

        if (!(_pf_user_login_password.isEditable())) {
            _tf_user_login_username.grabFocus();
        }

    }//GEN-LAST:event__pf_user_login_passwordMouseClicked

    private void tf_qrPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tf_qrPropertyChange


    }//GEN-LAST:event_tf_qrPropertyChange

    private void tf_rfPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tf_rfPropertyChange


    }//GEN-LAST:event_tf_rfPropertyChange

    private void tf_manuwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_manuwalActionPerformed

        if (tf_manuwal.getText().length() == 16) {
            sendToDb(jLabel7, tf_manuwal.getText());
            tf_manuwal.setText(null);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Invalide Entry");
        }

    }//GEN-LAST:event_tf_manuwalActionPerformed

    private void tf_rfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_rfKeyTyped

        if (tf_rf.getText().length() == 16) {
            sendToDb(jLabel17, tf_rf.getText());
            tf_rf.setText(null);
        }

    }//GEN-LAST:event_tf_rfKeyTyped

    private void tf_qrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_qrKeyTyped


    }//GEN-LAST:event_tf_qrKeyTyped

    private void tf_qrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_qrKeyReleased

        if (tf_qr.getText().length() == 16) {
            sendToDb(jLabel16, tf_qr.getText());
            tf_qr.setText(null);
        }

    }//GEN-LAST:event_tf_qrKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _lb_user_login_showPassword;
    private javax.swing.JPasswordField _pf_user_login_password;
    private javax.swing.JTextField _tf_user_login_username;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    public static javax.swing.JCheckBox jc_manual;
    public static javax.swing.JCheckBox jc_qr;
    public static javax.swing.JCheckBox jc_rf;
    private javax.swing.JLabel lb_ok_id;
    private javax.swing.JPanel logging;
    private javax.swing.JTextField tf_manuwal;
    private javax.swing.JTextField tf_qr;
    private javax.swing.JTextField tf_rf;
    // End of variables declaration//GEN-END:variables

    private void sendToDb(JLabel lb_name, String id) {
        Date da = new Date();

        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat sdf1 = new SimpleDateFormat("hh-mm-ss");
        String Fullname = "";
        String batch = "";
        String year = "";
        String cours = "";
        String firstTowName = "";
        String time = sdf1.format(da);
        String date = sdf.format(da);

        try {
            ResultSet name = MC_JavaDataBaseConnection.myConnection().createStatement().executeQuery(" SELECT * FROM `stu_info_name` where stu_user_info_id='" + id + "'");
            ResultSet batchAll = MC_JavaDataBaseConnection.myConnection().createStatement().executeQuery(" SELECT * FROM `stu_info_batch` where stu_user_info_id='" + id + "'");
            if (name.next()) {
                Fullname = name.getString("stu_info_name_first_name") + " " + name.getString("stu_info_name_last_name") + " " + name.getString("stu_info_name_sirName");
            }
            if (batchAll.next()) {
                batch = batchAll.getString("stu_info_batch");
                year = batchAll.getString("stu_info_year");
                cours = batchAll.getString("stu_info_course");
            }
            ResultSet rs = MC_JavaDataBaseConnection.myConnection().createStatement().executeQuery("select * from atendence where student_id='" + id + "' and date='" + date + "'");
            if (!(rs.next())) {
                
                MC_JavaDataBaseConnection.myConnection().createStatement().executeUpdate("INSERT INTO atendence (student_id,student_name,course,status,batch,year,date,time) VALUES ('" + id + "','" + Fullname + "','" + cours + "','1','" + batch + "','" + year + "','" + date + "','" + time + "')");
                firstTowName = name.getString("stu_info_name_first_name") + " " + name.getString("stu_info_name_last_name");
                lb_name.setText(firstTowName);
                lb_ok_id.setVisible(true);
                speekName(firstTowName);
                Thread.sleep(3000);
                lb_ok_id.setVisible(false);
                
            } else {
                if (!(rs.getString("out_state").equals("1"))) {
                    System.out.println("oooooo");
                    MC_JavaDataBaseConnection.myConnection().createStatement().executeUpdate("UPDATE `atendence` SET out_time='" + time + "',out_state='1' where student_id='"+id+"'");
                  
                    Voice voice;
                    VoiceManager vm = VoiceManager.getInstance();
                    voice = vm.getVoice(VOICENAME);

                    voice.allocate();

                    try {
                        firstTowName = name.getString("stu_info_name_first_name") + " " + name.getString("stu_info_name_last_name");
                         lb_name.setText(firstTowName);
                        voice.speak("Good Bye "+ firstTowName);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
                
                else{
                
                 Voice voice;
                    VoiceManager vm = VoiceManager.getInstance();
                    voice = vm.getVoice(VOICENAME);

                    voice.allocate();

                    try {
                        voice.speak("Sorry Invalide Entry");
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                
                }
                
                
                
                    
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void speekName(String firstTowName) {
        Voice voice;
        VoiceManager vm = VoiceManager.getInstance();
        voice = vm.getVoice(VOICENAME);

        voice.allocate();

        try {
            voice.speak("WelCome " + firstTowName);
        } catch (Exception e) {
        }
    }
}
