/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fgs.fsc_attendencesystem;

import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.awt.Color;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author deepalsuranga
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public static boolean flag = false;
    private static final String VOICENAME = "kevin16";

    public index() {
        initComponents();
        load_Login();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_main = new javax.swing.JPanel();
        Panel_Header = new javax.swing.JPanel();
        Bt_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JP_main.setBackground(new java.awt.Color(30, 136, 229));
        JP_main.setToolTipText("");
        JP_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(JP_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1366, 730));

        Panel_Header.setBackground(new java.awt.Color(26, 35, 126));
        Panel_Header.setFocusTraversalPolicyProvider(true);
        Panel_Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bt_close.setBackground(new java.awt.Color(61, 61, 61));
        Bt_close.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Bt_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ic_close.png"))); // NOI18N
        Bt_close.setBorderPainted(false);
        Bt_close.setFocusPainted(false);
        Bt_close.setPreferredSize(new java.awt.Dimension(24, 24));
        Bt_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bt_closeMousePressed(evt);
            }
        });
        Bt_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_closeActionPerformed(evt);
            }
        });
        Panel_Header.add(Bt_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 10, 24, 24));

        getContentPane().add(Panel_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Bt_closeActionPerformed

    private void Bt_closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_closeMousePressed
        
    }//GEN-LAST:event_Bt_closeMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_close;
    public static javax.swing.JPanel JP_main;
    private javax.swing.JPanel Panel_Header;
    // End of variables declaration//GEN-END:variables

    private void load_Login() {
        JP_Welcome welcome=new JP_Welcome();
        
        JP_main.removeAll();
        GroupLayout layout = new GroupLayout(JP_main);
        JP_main.setLayout(layout);

        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(welcome, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(welcome, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }

}
