/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fgs.fsc_attendencesystem;

/**
 *
 * @author Pamitha Gayashan
 */
public class JP_Attendance extends javax.swing.JPanel {

    /**
     * Creates new form Attendance
     */
    public JP_Attendance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_student_details_main = new javax.swing.JPanel();
        Panel_student_details_header = new javax.swing.JPanel();
        Label_student_details = new javax.swing.JLabel();
        Label_Name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_student_details_main.setBackground(new java.awt.Color(51, 51, 51));
        Panel_student_details_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Panel_student_details_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_student_details_header.setBackground(new java.awt.Color(51, 51, 51));
        Panel_student_details_header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Label_student_details.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Label_student_details.setForeground(new java.awt.Color(255, 255, 255));
        Label_student_details.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_student_details.setText("Student Details");

        javax.swing.GroupLayout Panel_student_details_headerLayout = new javax.swing.GroupLayout(Panel_student_details_header);
        Panel_student_details_header.setLayout(Panel_student_details_headerLayout);
        Panel_student_details_headerLayout.setHorizontalGroup(
            Panel_student_details_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_student_details_headerLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(Label_student_details, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        Panel_student_details_headerLayout.setVerticalGroup(
            Panel_student_details_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_student_details_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_student_details, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_student_details_main.add(Panel_student_details_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 80));

        Label_Name.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Label_Name.setText("Name");
        Panel_student_details_main.add(Label_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 130, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Class");
        Panel_student_details_main.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Month");
        Panel_student_details_main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Week");
        Panel_student_details_main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, 20));

        add(Panel_student_details_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 11, 660, 680));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Name;
    private javax.swing.JLabel Label_student_details;
    private javax.swing.JPanel Panel_student_details_header;
    private javax.swing.JPanel Panel_student_details_main;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
